@startuml

title Greenshop Domain Class Modell
'https://plantuml.com/class-diagram

left to right direction
'top to bottom direction

scale 1200 width

package org.woehlke.greenshop.oodm {

    package org.woehlke.greenshop.oodm.admin.entities {

          entity Administrator {
               - String nameDe
               - String nameEn
              list()
              search()
              addNew()
              edit()
              delete()
          }
          entity TaxClass {
              - String name
              - String description
              list()
              search()
              addNew()
              edit()
              delete()
          }
          entity TaxRate {
              - String name
              - String description
              list()
              search()
              addNew()
              edit()
              delete()
          }
          entity TaxZone {
             - String messageText
             - Boolean readByReceiver
              list()
              search()
              addNew()
              edit()
              delete()
          }
          entity TaxZone2Zone {
              - String userEmail
              - String userPassword
              - String userFullname
              - Language defaultLanguage
              - Date lastLoginTimestamp
              - Boolean accountNonExpired
              - Boolean accountNonLocked
              - Boolean credentialsNonExpired
              - Boolean enabled
              list()
              search()
              addNew()
              edit()
              delete()
          }
    }

    package org.woehlke.greenshop.oodm.cart.entities {

          entity CustomersBasket {
              - String userPassword
              list()
              search()
              addNew()
              edit()
              delete()
          }
          entity CustomersBasketAttribute {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
          }
    }

    package org.woehlke.greenshop.oodm.catalog.entities {

         entity Category {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity CategoryDescription {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class CategoryDescriptionId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Language {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Manufacturer {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ManufacturerInfo {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class ManufacturerInfoId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Product {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductAttribute {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductDescription {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class ProductDescriptionId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductImage {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductOption {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class ProductOptionId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductOptionValue {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductOptionValue2ProductOption {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class ProductOptionValueId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Review {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ReviewDescription {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class ReviewDescriptionId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Special {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
    }

    package org.woehlke.greenshop.oodm.checkout.entities {

         entity Order {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity OrderProduct {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity OrderProductAttribute {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity OrderStatus {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity OrderStatusHistory {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity OrderStatusId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity OrderTotal {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
    }

    package org.woehlke.greenshop.oodm.customer.entities {

         entity AddressBook {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity AddressFormat {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Country {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Customer {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity CustomerInfo {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity ProductNotification {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         class ProductNotificationId {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
         }
         entity Zone {
              - String email
              - String token
              - Integer numberOfRetries
              list()
              search()
              addNew()
              edit()
              delete()
        }
    }
}

@enduml
