server:
  port: 8080
  error:
    path: /fehler
  compression:
    enabled: true
    min-response-size: 2048
  servlet:
    context-path: "/"
  endpoints:
    shutdown:
      enabled: true
spring:
  config:
    name: greenshop
  liquibase:
    enabled: false
  devtools:
    livereload:
      enabled: true
  application:
    admin:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/oscommerce2
    username: oscommerce2
    password: oscommerce2pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jta:
  #  atomikos:
  #    connectionfactory:
  #      xa-connection-factory-class-name: com.mysql.jdbc.JDBC4Connection
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: MYSQL
    hibernate:
      #ddl-auto: create-drop update
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
      cleanup-cron: 0 * * * * *
      #schema: classpath:/org/springframework/session/jdbc/schema-h2.sql
      #table-name: SPRING_SESSION
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      platform: MYSQL
      mode: ALWAYS
org:
  woehlke:
    greenshop:
      testDataHowManyTestData: 10
      devTesting: true
      userConfig:
        userEmail: 'thomas.woehlke@gmail.com'
        userPassword: 'UHkIifHN3iXbZtoHhiPvPzeKFBpthm0eBXdvm+Q3xNrWyXRheGDLCw=='
        userFullname: 'Thomas Wöhlke'
      webConfig:
        exportFilename: "measurements.csv"
        exportFilenameSeparator: ";"
        webAddResourceHandlers:
          - "webjars/"
        webAddResourceHandlersStatic:
          - "greenshop/"
          - "icon/"
          - "languages/"
          - "test/"
          - "favicon.ico"
      webSecurity:
        loginProcessingUrl: "/j_spring_security_check"
        failureForwardUrl: "/login?login_error=1"
        defaultSuccessUrl: "/"
        login-page: "/login"
        logout-url: "/logout"
        delete-cookies: "JSESSIONID"
        invalidate-http-session: true
        antMatchersFullyAuthenticated: "/**"
        antMatchersPermitAll:
          - "/greenshop"
          - "/greenshop/**"
          - "/icon/**"
          - "/icon"
          - "/languages"
          - "/languages/**"
          - "/favicon.ico"
          - "/webjars/**"
          - "/webjars"
          - "/test*/**"
          - "/rest"
          - "/rest/**"
          - "/bpm"
          - "/login*"
          - "/register*"
          - "/confirm*/**"
          - "/resetPassword*"
          - "/passwordResetConfirm*/**"
          - "/error*"
          - "/fehler*"
        usernameParameter: "userEmail"
        passwordParameter: "userPassword"
        secret: '25D8484AB208F08C59FFAFE57DB9FF87'
        iterations: 4096
        hashWidth: 256
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      mysql: WARN
      greenshop:
        java:
          greenshop: INFO
debug: false
---
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  application:
    admin:
      enabled: false
server:
  compression:
    enabled: false
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      postgresql: WARN
      woehlke:
        java:
          greenshop: INFO
debug: false
---
spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/oscommerce2
  jta:
    atomikos:
      properties:
        transaction-manager-unique-name: tx-manager-bloodmoney
    transaction-manager-id: tx-manager-bloodmoney
    log-dir: transaction-logs/tx-logs-bloodmoney
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT}
  compression:
    enabled: true
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        engine:
          internal: WARN
      ch:
        qos: WARN
      woehlke:
        java:
          bloodmoney: INFO
debug: false
